# Application
spring.application.name=MarketSphere

# Server
server.port=8080

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/marketsphere_db
spring.datasource.username=root
spring.datasource.password=prerna@31
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui